[workspace]
members = [
	"rust/hypertask_config_file_opener",
	"rust/hypertask_engine",

	"rust/hypertask_client_cli",
	"rust/hypertask_client_js",

	"rust/hypertask_sync_daemon",
	"rust/hypertask_sync_server",
]

default-run = "task"
