[workspace]
members = [
	"rust/render_simple_cli_table",

	"rust/hypertask_config_file_opener",
	"rust/hypertask_engine",

	"rust/hypertask_client_cli",
	#"rust/hypertask_client_js",

	#"rust/hypertask_sync_daemon",
	"rust/hypertask_sync_server",
]
