[package]
name = "hypertask"
version = "0.1.0"
authors = ["Freddie Ridell <contact@freddieridell.com>"]
edition = "2018"
exclude = [ "target/**/*" ]


[[bin]]
name = "task"
path = "src/main.rs"

[dependencies]
ansi_term = "0.11"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.3.0"
rand = "0.6.5" 
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
time = "0.1.42"

