[package]
name = "hypertask_sync_server"
version = "0.1.0"
authors = ["Freddie Ridell <contact@freddieridell.com>"]
edition = "2018"

[[bin]]
name = "hypertask-sync-server"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
hypertask_engine={ version = "0.2.0", path= "../../lib/engine" }
platform-dirs = "0.2"
rand = "0.6" 
time = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
shellexpand = "1"
daemonize = "0.4"
tide = "0.6.0"
async-std = "1.5.0"
log = "0.4.8"
env_logger = "0.7.1"
futures = "0.3.4"

[dependencies.clap]
git = 'https://github.com/clap-rs/clap.git'
branch = 'master'
