[package]
name = "hypercortex_engine"
version = "0.1.0"
authors = ["Freddie Ridell <contact@freddieridell.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5" 
chrono = { version = "0.4", features = ["serde"] }
