[package]
name = 'hypertask_sync_client_cli'
version = '0.1.0'
authors = ['Freddie Ridell <contact@freddieridell.com>']
edition = '2018'

[[bin]]
name = 'hypertask-sync-client'
path = 'src/main.rs'

[dependencies]
daemonize = '0.4'
platform-dirs = '0.2'
shellexpand = '1'
surf = '1'
async-std = '1.1'
chrono = '0.4'
time = '0.1'
log = '0.4.8'
env_logger = '0.7.1'
futures = '0.3.4'
notify = '4'

[dependencies.simple_persist_data]
path = '../../../../simple_persist_data'
features = [ "json" ]

[dependencies.serde]
version = '1'
features = ['derive']

[dependencies.hypertask_engine]
version = '0.2.0'
path = '../../lib/engine'

[dependencies.hypertask_sync_storage_with_server]
version = '0.1.0'
path = '../../lib/sync_with_server'

[dependencies.serde_json]
version = '1'

[dependencies.clap]
git = 'https://github.com/clap-rs/clap.git'
branch = 'master'
